### ISSUE TITLE
Update site is 404

### ISSUE THREAD

**Issue by potmo** [mrpotes/cukes-jvm-eclipse-plugin#18]
The update site: http://mrpotes.github.com/cukes-jvm-eclipse-plugin/update-site/ gives a 404

**Comment by mrpotes** [comment]
Yes - there's no default content there for a browser. You need to put it into eclipse, which should then find the site content. I ought to change the plugin homepage to not have a link to the update site, just the URL in plain text.

**Comment by potmo** [comment]
It don't work in eclipse for me ether. Eclipse says it's a dead link.

**Comment by mrpotes** [comment]
Strange, it's working fine for me. What version of eclipse are you using?

**Comment by potmo** [comment]
Sorry. Now it actually works

**Comment by mrpotes** [comment]
That's good. Hope it works ok for you :)
