### ISSUE TITLE
Unable to add site in Eclipse

### ISSUE THREAD

**Issue by mumar** [mrpotes/cukes-jvm-eclipse-plugin#23]
I am unable to add this plugin in Eclipse. 

I get a site error msg every time.

**Comment by mrpotes** [comment]
What is the exact URL are you adding?

**Comment by mumar** [comment]
I am using this:

http://github.com/mrpotes/cukes-jvm-eclipse-plugin

**Comment by mrpotes** [comment]
That url isn't correct, you need /update-site on the end (right click copy
link location from the link on the website you found).

**Comment by mumar** [comment]
That worked...thanks!
